# -*- coding: utf-8 -*-
"""자동 생성 파일 — 직접 수정하지 말 것.

topics.json 을 고친 뒤 `py tools/build_topics.py` 로 다시 만든다.
출제 학원명(src)은 의도적으로 제외되어 있다.
"""

TOPICS = [{'no': 1, 'area': '취향', 'topic': 'Write about your favorite book.', 'isNew': False},
 {'no': 2, 'area': '취향', 'topic': 'Write about your favorite meal.', 'isNew': False},
 {'no': 3, 'area': '취향', 'topic': 'Write about your favorite season.', 'isNew': False},
 {'no': 4, 'area': '취향', 'topic': 'Write about your favorite wild animal.', 'isNew': False},
 {'no': 5, 'area': '취향', 'topic': 'What is your favorite thing to do?', 'isNew': False},
 {'no': 6,
  'area': '취향',
  'topic': 'Write about your favorite vacation with your family.',
  'isNew': False},
 {'no': 7,
  'area': '취향',
  'topic': 'What is your favorite animal, and what led you to like it? Describe the reasons behind '
           'your fondness for that animal.',
  'isNew': False},
 {'no': 8, 'area': '취향', 'topic': 'Write about your favorite holiday.', 'isNew': False},
 {'no': 9, 'area': '취향', 'topic': 'What is your favorite hobby?', 'isNew': False},
 {'no': 10,
  'area': '취향',
  'topic': 'Write about your favorite character from a book or movie.',
  'isNew': False},
 {'no': 11, 'area': '취향', 'topic': 'What is your favorite toy?', 'isNew': False},
 {'no': 12,
  'area': '취향',
  'topic': 'Do you prefer indoor activities or outdoor activities? Write about one activity you '
           'enjoy and explain why.',
  'isNew': False},
 {'no': 13, 'area': '취향', 'topic': 'Do you prefer cats or dogs?', 'isNew': False},
 {'no': 14,
  'area': '취향',
  'topic': 'Write a story about your favorite day of school.',
  'isNew': False},
 {'no': 15,
  'area': '취향',
  'topic': 'What is your favorite holiday and the least favorite one out of the year?',
  'isNew': False},
 {'no': 16, 'area': '취향', 'topic': 'Who is your favorite teacher, and why?', 'isNew': False},
 {'no': 17, 'area': '취향', 'topic': 'Explain your favorite subject and why.', 'isNew': False},
 {'no': 18, 'area': '취향', 'topic': 'Explain how to play your favorite video game.', 'isNew': False},
 {'no': 19, 'area': '취향', 'topic': 'Which season do you like the best, and why?', 'isNew': False},
 {'no': 20,
  'area': '취향',
  'topic': 'At the ice cream place, what flavor is your favorite, and why?',
  'isNew': False},
 {'no': 21, 'area': '취향', 'topic': 'What is your favorite color, and why?', 'isNew': True},
 {'no': 22, 'area': '취향', 'topic': 'Write about your favorite sport.', 'isNew': True},
 {'no': 23, 'area': '취향', 'topic': 'What is your favorite drink?', 'isNew': True},
 {'no': 24, 'area': '취향', 'topic': 'Write about your favorite place to visit.', 'isNew': True},
 {'no': 25,
  'area': '취향',
  'topic': 'What is your favorite app or game on your phone/tablet?',
  'isNew': True},
 {'no': 26, 'area': '취향', 'topic': 'Write about your favorite family member.', 'isNew': True},
 {'no': 27,
  'area': '취향',
  'topic': 'What is your favorite school subject to study at home?',
  'isNew': True},
 {'no': 28, 'area': '취향', 'topic': 'Write about your favorite song or singer.', 'isNew': True},
 {'no': 29,
  'area': '취향',
  'topic': 'What is your favorite way to spend the weekend?',
  'isNew': True},
 {'no': 30,
  'area': '취향',
  'topic': 'Write about your favorite outfit or piece of clothing.',
  'isNew': True},
 {'no': 31, 'area': '상상', 'topic': 'What if you were on a sinking ship?', 'isNew': False},
 {'no': 32, 'area': '상상', 'topic': 'What if there were flying cows?', 'isNew': False},
 {'no': 33, 'area': '상상', 'topic': 'What if toys could talk?', 'isNew': False},
 {'no': 34, 'area': '상상', 'topic': 'How would it feel if you could fly?', 'isNew': False},
 {'no': 35,
  'area': '상상',
  'topic': 'If you encountered a lost monster, would you help it?',
  'isNew': False},
 {'no': 36,
  'area': '상상',
  'topic': 'What would happen if you planted a magic seed?',
  'isNew': False},
 {'no': 37,
  'area': '상상',
  'topic': 'What if I had a magical potion that allowed me to time travel?',
  'isNew': False},
 {'no': 38,
  'area': '상상',
  'topic': 'What would your life look like if you became the richest person in the world?',
  'isNew': False},
 {'no': 39,
  'area': '상상',
  'topic': 'What if you wake up and realize that you have superpowers?',
  'isNew': False},
 {'no': 40,
  'area': '상상',
  'topic': 'What if you found something sparkling in the field?',
  'isNew': False},
 {'no': 41, 'area': '상상', 'topic': 'What would you teach if you were a teacher?', 'isNew': False},
 {'no': 42, 'area': '상상', 'topic': 'What would happen if you became 5cm tall?', 'isNew': False},
 {'no': 43, 'area': '상상', 'topic': 'Imagine you found a magic box. Write a story.', 'isNew': False},
 {'no': 44,
  'area': '상상',
  'topic': 'Imagine you came home from school and your bedroom is covered with chocolate. How '
           'would you clean up the mess?',
  'isNew': False},
 {'no': 45,
  'area': '상상',
  'topic': 'What would you do if you had a fight with your mother?',
  'isNew': False},
 {'no': 46,
  'area': '상상',
  'topic': 'What would you do if a dragon tried to attack you?',
  'isNew': False},
 {'no': 47,
  'area': '상상',
  'topic': 'If you could travel anywhere, where would you like to go and why?',
  'isNew': False},
 {'no': 48,
  'area': '상상',
  'topic': 'If you could fly, what would your life be like?',
  'isNew': False},
 {'no': 49,
  'area': '상상',
  'topic': "If you could change your nationality, which country's nationality would you like to "
           'switch to and why?',
  'isNew': False},
 {'no': 50,
  'area': '상상',
  'topic': 'Would you like to write a story about what the world might be like 500 years from now?',
  'isNew': False},
 {'no': 51,
  'area': '상상',
  'topic': 'If a monster lived next door, could you become friends with him or her?',
  'isNew': False},
 {'no': 52,
  'area': '상상',
  'topic': 'What if you became invisible? What would you like to do?',
  'isNew': False},
 {'no': 53,
  'area': '상상',
  'topic': 'What if you found a treasure map, what would you like to do?',
  'isNew': False},
 {'no': 54,
  'area': '상상',
  'topic': 'If you had a magic bean, what are the two wishes you would ask for?',
  'isNew': False},
 {'no': 55, 'area': '상상', 'topic': 'If you had a time machine, what would you do?', 'isNew': False},
 {'no': 56,
  'area': '상상',
  'topic': 'If you could go back to the past and meet someone famous, who would you like to meet?',
  'isNew': False},
 {'no': 57,
  'area': '상상',
  'topic': 'If you could have one type of pet, what would you like to have and why?',
  'isNew': False},
 {'no': 58,
  'area': '상상',
  'topic': 'One day, all adults are gone, and children should rule the world. What would you do?',
  'isNew': False},
 {'no': 59,
  'area': '상상',
  'topic': 'If you could have lunch with anyone in the world, who would you pick?',
  'isNew': False},
 {'no': 60,
  'area': '상상',
  'topic': 'If you were swallowed by a whale, what would you do?',
  'isNew': False},
 {'no': 61,
  'area': '상상',
  'topic': 'If you meet a Genie from Aladdin and your 3 wishes come true, what would your 3 wishes '
           'be, and why?',
  'isNew': False},
 {'no': 62,
  'area': '상상',
  'topic': 'If I became the richest person in the world, what would my life be like? Can you share '
           'specific ways of making money?',
  'isNew': False},
 {'no': 63,
  'area': '상상',
  'topic': 'If you were invisible for one day, what would you do?',
  'isNew': False},
 {'no': 64,
  'area': '상상',
  'topic': 'If you could be anybody in the world for one day, who would that be and why?',
  'isNew': False},
 {'no': 65,
  'area': '상상',
  'topic': "Can you describe what the last dinosaurs' life would be like on Earth?",
  'isNew': False},
 {'no': 66,
  'area': '상상',
  'topic': 'If you had a magic stone, what would your two wishes be?',
  'isNew': False},
 {'no': 67,
  'area': '상상',
  'topic': 'What would you do if a monster wanted to become friends with you?',
  'isNew': False},
 {'no': 68,
  'area': '상상',
  'topic': 'You took a nap after school and woke up on a pirate ship. What do you do?',
  'isNew': False},
 {'no': 69,
  'area': '상상',
  'topic': 'Imagine your parents have left you home alone for two weeks. What would you do?',
  'isNew': False},
 {'no': 70,
  'area': '상상',
  'topic': 'What would your life be like if you could fly?',
  'isNew': False},
 {'no': 71,
  'area': '상상',
  'topic': 'If you could go anywhere in the world, where would you go and what would you do?',
  'isNew': False},
 {'no': 72,
  'area': '상상',
  'topic': 'What changes would you make if you were the president of your country?',
  'isNew': False},
 {'no': 73,
  'area': '상상',
  'topic': 'If you were born again, would you be the same sex or change to the opposite sex, and '
           'why?',
  'isNew': False},
 {'no': 74,
  'area': '상상',
  'topic': 'If you found a pair of magical shoes, what would you do?',
  'isNew': False},
 {'no': 75,
  'area': '상상',
  'topic': 'There is a monster who is lost. What can you do to help him?',
  'isNew': False},
 {'no': 76,
  'area': '상상',
  'topic': 'If you could talk to animals, what would you say to your pet?',
  'isNew': True},
 {'no': 77, 'area': '상상', 'topic': 'What if it rained candy instead of water?', 'isNew': True},
 {'no': 78,
  'area': '상상',
  'topic': 'If you could build your own robot, what would it do?',
  'isNew': True},
 {'no': 79, 'area': '상상', 'topic': 'What if you woke up in a fairy tale world?', 'isNew': True},
 {'no': 80,
  'area': '상상',
  'topic': 'If you could live underwater, what would your house look like?',
  'isNew': True},
 {'no': 81, 'area': '경험', 'topic': 'What do you do in your free time?', 'isNew': False},
 {'no': 82, 'area': '경험', 'topic': 'Write about your most memorable event.', 'isNew': False},
 {'no': 83, 'area': '경험', 'topic': 'What will be different next year?', 'isNew': False},
 {'no': 84,
  'area': '경험',
  'topic': 'Write about the differences between last year and this year.',
  'isNew': False},
 {'no': 85,
  'area': '경험',
  'topic': 'How would you feel if your family went on a trip and you were alone for a week?',
  'isNew': False},
 {'no': 86,
  'area': '경험',
  'topic': 'Write about a gift you would like to get and the reasons why.',
  'isNew': False},
 {'no': 87,
  'area': '경험',
  'topic': 'Write about a time you received the best gift ever.',
  'isNew': False},
 {'no': 88, 'area': '경험', 'topic': 'What can I do if I have 20 dollars?', 'isNew': False},
 {'no': 89, 'area': '경험', 'topic': 'Write about the most memorable trip you had.', 'isNew': False},
 {'no': 90, 'area': '경험', 'topic': 'Describe a special memory.', 'isNew': False},
 {'no': 91,
  'area': '경험',
  'topic': 'What was the most memorable day this year, and why?',
  'isNew': False},
 {'no': 92, 'area': '경험', 'topic': 'Describe your first day of school.', 'isNew': False},
 {'no': 93, 'area': '경험', 'topic': 'What did you do during summer vacation?', 'isNew': False},
 {'no': 94, 'area': '경험', 'topic': 'Describe your daily routine after school.', 'isNew': True},
 {'no': 95, 'area': '경험', 'topic': 'Write about a time you helped someone.', 'isNew': True},
 {'no': 96,
  'area': '경험',
  'topic': 'What is the best meal your family has cooked together?',
  'isNew': True},
 {'no': 97, 'area': '경험', 'topic': 'Write about a time you felt proud of yourself.', 'isNew': True},
 {'no': 98, 'area': '경험', 'topic': 'Describe your favorite family tradition.', 'isNew': True},
 {'no': 99, 'area': '경험', 'topic': 'Write about a time you made a new friend.', 'isNew': True},
 {'no': 100, 'area': '경험', 'topic': 'What did you do last weekend?', 'isNew': True},
 {'no': 101,
  'area': '경험',
  'topic': 'Write about a time you were scared and how you overcame it.',
  'isNew': True},
 {'no': 102,
  'area': '경험',
  'topic': 'Describe a mistake you made and what you learned from it.',
  'isNew': True},
 {'no': 103,
  'area': '경험',
  'topic': 'Write about your favorite birthday celebration.',
  'isNew': True},
 {'no': 104, 'area': '경험', 'topic': 'What is something new you learned recently?', 'isNew': True},
 {'no': 105,
  'area': '경험',
  'topic': 'Write about a time you had to wait for something you really wanted.',
  'isNew': True},
 {'no': 106,
  'area': '자기소개',
  'topic': 'If you could have a sibling, who would you want to have?',
  'isNew': False},
 {'no': 107, 'area': '자기소개', 'topic': 'Would you rather have a brother or sister?', 'isNew': False},
 {'no': 108,
  'area': '자기소개',
  'topic': 'What would you like to give to your best friend?',
  'isNew': False},
 {'no': 109,
  'area': '자기소개',
  'topic': 'What are some good ways to live a long and healthy life?',
  'isNew': False},
 {'no': 110, 'area': '자기소개', 'topic': 'What are you thankful for?', 'isNew': False},
 {'no': 111,
  'area': '자기소개',
  'topic': 'Who is the most admirable person to you and why?',
  'isNew': False},
 {'no': 112,
  'area': '자기소개',
  'topic': 'Why is it important to always try your best?',
  'isNew': False},
 {'no': 113, 'area': '자기소개', 'topic': 'Why is honesty important?', 'isNew': False},
 {'no': 114,
  'area': '자기소개',
  'topic': 'What are the best qualities to have as a best friend?',
  'isNew': False},
 {'no': 115,
  'area': '자기소개',
  'topic': 'What kind of qualities do they need to be good teachers?',
  'isNew': False},
 {'no': 116, 'area': '자기소개', 'topic': 'What will you do and be 10 years later?', 'isNew': False},
 {'no': 117,
  'area': '자기소개',
  'topic': 'When your friend is feeling down and sad, what would you do?',
  'isNew': False},
 {'no': 118, 'area': '자기소개', 'topic': 'What are three words that describe you?', 'isNew': True},
 {'no': 119, 'area': '자기소개', 'topic': 'What is your biggest strength?', 'isNew': True},
 {'no': 120,
  'area': '자기소개',
  'topic': 'What is something you want to improve about yourself?',
  'isNew': True},
 {'no': 121, 'area': '자기소개', 'topic': 'Who inspires you the most, and why?', 'isNew': True},
 {'no': 122, 'area': '자기소개', 'topic': 'What is a rule you always follow, and why?', 'isNew': True},
 {'no': 123, 'area': '자기소개', 'topic': 'What makes you a good friend?', 'isNew': True},
 {'no': 124, 'area': '자기소개', 'topic': 'What is your dream job, and why?', 'isNew': True},
 {'no': 125, 'area': '자기소개', 'topic': 'What is something you are proud of?', 'isNew': True},
 {'no': 126,
  'area': '학교사회',
  'topic': 'What is a present you want to give to Santa?',
  'isNew': False},
 {'no': 127,
  'area': '학교사회',
  'topic': 'How is elementary school different from kindergarten?',
  'isNew': False},
 {'no': 128,
  'area': '학교사회',
  'topic': 'Between Seollal and Chuseok, which holiday is more important?',
  'isNew': False},
 {'no': 129,
  'area': '학교사회',
  'topic': 'Between playing hard and studying hard, which one is more important?',
  'isNew': False},
 {'no': 130,
  'area': '학교사회',
  'topic': 'Between being clever and being kind, which one is more important?',
  'isNew': False},
 {'no': 131, 'area': '학교사회', 'topic': 'Why is it important to work?', 'isNew': False},
 {'no': 132,
  'area': '학교사회',
  'topic': 'Why do you want to come to Think-Eng English academy?',
  'isNew': False},
 {'no': 133,
  'area': '학교사회',
  'topic': 'If all the adults in the world were to disappear, how would you feel?',
  'isNew': False},
 {'no': 134,
  'area': '학교사회',
  'topic': 'Write a story about a man finding a secret door.',
  'isNew': False},
 {'no': 135,
  'area': '학교사회',
  'topic': "What would you do on a holiday? It needs to be a holiday that doesn't exist.",
  'isNew': False},
 {'no': 136, 'area': '학교사회', 'topic': 'Describe three things about you.', 'isNew': False},
 {'no': 137,
  'area': '학교사회',
  'topic': 'What are two things you want to teach your friend?',
  'isNew': False},
 {'no': 138,
  'area': '학교사회',
  'topic': 'How would you explain your good talent to others?',
  'isNew': False},
 {'no': 139,
  'area': '학교사회',
  'topic': 'How would your life change if you shrunk to the size of a hand?',
  'isNew': False},
 {'no': 140,
  'area': '학교사회',
  'topic': 'If a witch turned your friend into a hamster, how would you help him/her?',
  'isNew': False},
 {'no': 141,
  'area': '학교사회',
  'topic': 'What would you do if a tiny person as small as your hand sank you down in the water?',
  'isNew': False},
 {'no': 142,
  'area': '학교사회',
  'topic': 'How would you explain what you do well to a friend of yours?',
  'isNew': False},
 {'no': 143,
  'area': '학교사회',
  'topic': "If we didn't go to school anymore, how do you think your daily life and life in "
           'general would change?',
  'isNew': False},
 {'no': 144,
  'area': '학교사회',
  'topic': 'If you are a superhero, what kind of power would you like to have?',
  'isNew': False},
 {'no': 145,
  'area': '학교사회',
  'topic': 'If the Earth is getting polluted, what would you do to save it?',
  'isNew': False},
 {'no': 146,
  'area': '학교사회',
  'topic': 'Should your parents let you watch TV whenever you want?',
  'isNew': False},
 {'no': 147,
  'area': '학교사회',
  'topic': 'Is it better to work alone or work with others?',
  'isNew': False},
 {'no': 148,
  'area': '학교사회',
  'topic': 'Give three reasons why students should have homework.',
  'isNew': False},
 {'no': 149,
  'area': '학교사회',
  'topic': 'Why should homework be done before watching TV?',
  'isNew': False},
 {'no': 150, 'area': '학교사회', 'topic': 'Why should we exercise?', 'isNew': False},
 {'no': 151,
  'area': '학교사회',
  'topic': 'Why do you think that learning English is important? And what can you do when you '
           'learn English?',
  'isNew': False},
 {'no': 152,
  'area': '학교사회',
  'topic': 'If you can travel anywhere in your country, where do you want to go and why?',
  'isNew': False},
 {'no': 153,
  'area': '학교사회',
  'topic': 'What do you think about the global pandemic? Throughout history, what was the most '
           "famous pandemic's solution and lesson about that?",
  'isNew': False},
 {'no': 154,
  'area': '학교사회',
  'topic': 'If toys could be alive on the night of Halloween, what would you do and why?',
  'isNew': False},
 {'no': 155, 'area': '학교사회', 'topic': 'Describe what your city/town looks like.', 'isNew': False},
 {'no': 156,
  'area': '학교사회',
  'topic': 'If something could disappear from the world, what would it be?',
  'isNew': False},
 {'no': 157,
  'area': '학교사회',
  'topic': 'If you could pick some subjects that you should learn, what would they be, and why?',
  'isNew': False},
 {'no': 158, 'area': '학교사회', 'topic': 'What rules should every classroom have?', 'isNew': True},
 {'no': 159, 'area': '학교사회', 'topic': 'Why is it important to help classmates?', 'isNew': True},
 {'no': 160, 'area': '학교사회', 'topic': 'Should students wear school uniforms?', 'isNew': True},
 {'no': 161, 'area': '학교사회', 'topic': 'What makes a good leader?', 'isNew': True},
 {'no': 162, 'area': '학교사회', 'topic': 'Why is recycling important?', 'isNew': True},
 {'no': 163,
  'area': '학교사회',
  'topic': 'What can students do to help the environment?',
  'isNew': True},
 {'no': 164,
  'area': '학교사회',
  'topic': 'Should students be allowed to choose their own subjects?',
  'isNew': True},
 {'no': 165, 'area': '학교사회', 'topic': 'Why is teamwork important in school?', 'isNew': True}]
