# -*- coding: utf-8 -*-
"""자동 생성 파일 — 직접 수정하지 말 것.

서버 전용 주제 정보. 출제 학원명(src)을 포함하므로
브라우저로 내보내는 응답에 절대 넣지 말 것.
PDF 헤더의 "Past Test · {학원명}" 표기에만 쓴다.
"""

TOPICS_BY_NO = {1: {'no': 1, 'area': '취향', 'topic': 'Write about your favorite book.', 'src': 'ILE'},
 2: {'no': 2, 'area': '취향', 'topic': 'Write about your favorite meal.', 'src': 'ILE'},
 3: {'no': 3, 'area': '취향', 'topic': 'Write about your favorite season.', 'src': 'MI'},
 4: {'no': 4, 'area': '취향', 'topic': 'Write about your favorite wild animal.', 'src': 'MI'},
 5: {'no': 5, 'area': '취향', 'topic': 'What is your favorite thing to do?', 'src': '띵킹어학원'},
 6: {'no': 6,
     'area': '취향',
     'topic': 'Write about your favorite vacation with your family.',
     'src': '렉스킴'},
 7: {'no': 7,
     'area': '취향',
     'topic': 'What is your favorite animal, and what led you to like it? Describe the reasons '
              'behind your fondness for that animal.',
     'src': '렉스킴'},
 8: {'no': 8, 'area': '취향', 'topic': 'Write about your favorite holiday.', 'src': '렉스킴'},
 9: {'no': 9, 'area': '취향', 'topic': 'What is your favorite hobby?', 'src': '렉스킴'},
 10: {'no': 10,
      'area': '취향',
      'topic': 'Write about your favorite character from a book or movie.',
      'src': '렉스킴'},
 11: {'no': 11, 'area': '취향', 'topic': 'What is your favorite toy?', 'src': '서초 피아이'},
 12: {'no': 12,
      'area': '취향',
      'topic': 'Do you prefer indoor activities or outdoor activities? Write about one activity '
               'you enjoy and explain why.',
      'src': '서초 피아이'},
 13: {'no': 13, 'area': '취향', 'topic': 'Do you prefer cats or dogs?', 'src': '스와튼'},
 14: {'no': 14,
      'area': '취향',
      'topic': 'Write a story about your favorite day of school.',
      'src': '스와튼'},
 15: {'no': 15,
      'area': '취향',
      'topic': 'What is your favorite holiday and the least favorite one out of the year?',
      'src': '아이앤'},
 16: {'no': 16, 'area': '취향', 'topic': 'Who is your favorite teacher, and why?', 'src': '아이앤'},
 17: {'no': 17, 'area': '취향', 'topic': 'Explain your favorite subject and why.', 'src': '아이앤'},
 18: {'no': 18,
      'area': '취향',
      'topic': 'Explain how to play your favorite video game.',
      'src': '알파'},
 19: {'no': 19, 'area': '취향', 'topic': 'Which season do you like the best, and why?', 'src': '알파'},
 20: {'no': 20,
      'area': '취향',
      'topic': 'At the ice cream place, what flavor is your favorite, and why?',
      'src': '알파'},
 21: {'no': 21, 'area': '취향', 'topic': 'What is your favorite color, and why?', 'src': '알파'},
 22: {'no': 22, 'area': '취향', 'topic': 'Write about your favorite sport.', 'src': '알파'},
 23: {'no': 23, 'area': '취향', 'topic': 'What is your favorite drink?', 'src': '알파'},
 24: {'no': 24, 'area': '취향', 'topic': 'Write about your favorite place to visit.', 'src': '에디센'},
 25: {'no': 25,
      'area': '취향',
      'topic': 'What is your favorite app or game on your phone/tablet?',
      'src': '이맥스'},
 26: {'no': 26, 'area': '취향', 'topic': 'Write about your favorite family member.', 'src': '이맥스'},
 27: {'no': 27,
      'area': '취향',
      'topic': 'What is your favorite school subject to study at home?',
      'src': '인사이트'},
 28: {'no': 28, 'area': '취향', 'topic': 'Write about your favorite song or singer.', 'src': '인사이트'},
 29: {'no': 29,
      'area': '취향',
      'topic': 'What is your favorite way to spend the weekend?',
      'src': '제이프렙'},
 30: {'no': 30,
      'area': '취향',
      'topic': 'Write about your favorite outfit or piece of clothing.',
      'src': '트윈클'},
 31: {'no': 31, 'area': '상상', 'topic': 'What if you were on a sinking ship?', 'src': 'ILE'},
 32: {'no': 32, 'area': '상상', 'topic': 'What if there were flying cows?', 'src': 'ILE'},
 33: {'no': 33, 'area': '상상', 'topic': 'What if toys could talk?', 'src': 'ILE'},
 34: {'no': 34, 'area': '상상', 'topic': 'How would it feel if you could fly?', 'src': 'ILE'},
 35: {'no': 35,
      'area': '상상',
      'topic': 'If you encountered a lost monster, would you help it?',
      'src': 'MI'},
 36: {'no': 36,
      'area': '상상',
      'topic': 'What would happen if you planted a magic seed?',
      'src': 'MI'},
 37: {'no': 37,
      'area': '상상',
      'topic': 'What if I had a magical potion that allowed me to time travel?',
      'src': '띵킹어학원'},
 38: {'no': 38,
      'area': '상상',
      'topic': 'What would your life look like if you became the richest person in the world?',
      'src': '렉스킴'},
 39: {'no': 39,
      'area': '상상',
      'topic': 'What if you wake up and realize that you have superpowers?',
      'src': '렉스킴'},
 40: {'no': 40,
      'area': '상상',
      'topic': 'What if you found something sparkling in the field?',
      'src': '서초 피아이'},
 41: {'no': 41,
      'area': '상상',
      'topic': 'What would you teach if you were a teacher?',
      'src': '서초 피아이'},
 42: {'no': 42, 'area': '상상', 'topic': 'What would happen if you became 5cm tall?', 'src': '스와튼'},
 43: {'no': 43,
      'area': '상상',
      'topic': 'Imagine you found a magic box. Write a story.',
      'src': '스와튼'},
 44: {'no': 44,
      'area': '상상',
      'topic': 'Imagine you came home from school and your bedroom is covered with chocolate. How '
               'would you clean up the mess?',
      'src': '스와튼'},
 45: {'no': 45,
      'area': '상상',
      'topic': 'What would you do if you had a fight with your mother?',
      'src': '스와튼'},
 46: {'no': 46,
      'area': '상상',
      'topic': 'What would you do if a dragon tried to attack you?',
      'src': '아이앤'},
 47: {'no': 47,
      'area': '상상',
      'topic': 'If you could travel anywhere, where would you like to go and why?',
      'src': '아이앤'},
 48: {'no': 48,
      'area': '상상',
      'topic': 'If you could fly, what would your life be like?',
      'src': '아이앤'},
 49: {'no': 49,
      'area': '상상',
      'topic': "If you could change your nationality, which country's nationality would you like "
               'to switch to and why?',
      'src': '아이앤'},
 50: {'no': 50,
      'area': '상상',
      'topic': 'Would you like to write a story about what the world might be like 500 years from '
               'now?',
      'src': '아이앤'},
 51: {'no': 51,
      'area': '상상',
      'topic': 'If a monster lived next door, could you become friends with him or her?',
      'src': '알파'},
 52: {'no': 52,
      'area': '상상',
      'topic': 'What if you became invisible? What would you like to do?',
      'src': '알파'},
 53: {'no': 53,
      'area': '상상',
      'topic': 'What if you found a treasure map, what would you like to do?',
      'src': '에디센'},
 54: {'no': 54,
      'area': '상상',
      'topic': 'If you had a magic bean, what are the two wishes you would ask for?',
      'src': '에디센'},
 55: {'no': 55,
      'area': '상상',
      'topic': 'If you had a time machine, what would you do?',
      'src': '에디센'},
 56: {'no': 56,
      'area': '상상',
      'topic': 'If you could go back to the past and meet someone famous, who would you like to '
               'meet?',
      'src': '에디센'},
 57: {'no': 57,
      'area': '상상',
      'topic': 'If you could have one type of pet, what would you like to have and why?',
      'src': '에디센'},
 58: {'no': 58,
      'area': '상상',
      'topic': 'One day, all adults are gone, and children should rule the world. What would you '
               'do?',
      'src': '에디센'},
 59: {'no': 59,
      'area': '상상',
      'topic': 'If you could have lunch with anyone in the world, who would you pick?',
      'src': '에디센'},
 60: {'no': 60,
      'area': '상상',
      'topic': 'If you were swallowed by a whale, what would you do?',
      'src': '에디센'},
 61: {'no': 61,
      'area': '상상',
      'topic': 'If you meet a Genie from Aladdin and your 3 wishes come true, what would your 3 '
               'wishes be, and why?',
      'src': '에디센'},
 62: {'no': 62,
      'area': '상상',
      'topic': 'If I became the richest person in the world, what would my life be like? Can you '
               'share specific ways of making money?',
      'src': '이맥스'},
 63: {'no': 63,
      'area': '상상',
      'topic': 'If you were invisible for one day, what would you do?',
      'src': '이맥스'},
 64: {'no': 64,
      'area': '상상',
      'topic': 'If you could be anybody in the world for one day, who would that be and why?',
      'src': '이맥스'},
 65: {'no': 65,
      'area': '상상',
      'topic': "Can you describe what the last dinosaurs' life would be like on Earth?",
      'src': '이맥스'},
 66: {'no': 66,
      'area': '상상',
      'topic': 'If you had a magic stone, what would your two wishes be?',
      'src': '인사이트'},
 67: {'no': 67,
      'area': '상상',
      'topic': 'What would you do if a monster wanted to become friends with you?',
      'src': '인사이트'},
 68: {'no': 68,
      'area': '상상',
      'topic': 'You took a nap after school and woke up on a pirate ship. What do you do?',
      'src': '인사이트'},
 69: {'no': 69,
      'area': '상상',
      'topic': 'Imagine your parents have left you home alone for two weeks. What would you do?',
      'src': '제이프렙'},
 70: {'no': 70,
      'area': '상상',
      'topic': 'What would your life be like if you could fly?',
      'src': '제이프렙'},
 71: {'no': 71,
      'area': '상상',
      'topic': 'If you could go anywhere in the world, where would you go and what would you do?',
      'src': '제이프렙'},
 72: {'no': 72,
      'area': '상상',
      'topic': 'What changes would you make if you were the president of your country?',
      'src': '제이프렙'},
 73: {'no': 73,
      'area': '상상',
      'topic': 'If you were born again, would you be the same sex or change to the opposite sex, '
               'and why?',
      'src': '제이프렙'},
 74: {'no': 74,
      'area': '상상',
      'topic': 'If you found a pair of magical shoes, what would you do?',
      'src': '제이프렙'},
 75: {'no': 75,
      'area': '상상',
      'topic': 'There is a monster who is lost. What can you do to help him?',
      'src': '트윈클'},
 76: {'no': 76,
      'area': '상상',
      'topic': 'If you could talk to animals, what would you say to your pet?',
      'src': '트윈클'},
 77: {'no': 77, 'area': '상상', 'topic': 'What if it rained candy instead of water?', 'src': '트윈클'},
 78: {'no': 78,
      'area': '상상',
      'topic': 'If you could build your own robot, what would it do?',
      'src': '트윈클'},
 79: {'no': 79, 'area': '상상', 'topic': 'What if you woke up in a fairy tale world?', 'src': '트윈클'},
 80: {'no': 80,
      'area': '상상',
      'topic': 'If you could live underwater, what would your house look like?',
      'src': '트윈클'},
 81: {'no': 81, 'area': '경험', 'topic': 'What do you do in your free time?', 'src': 'ILE'},
 82: {'no': 82, 'area': '경험', 'topic': 'Write about your most memorable event.', 'src': 'ILE'},
 83: {'no': 83, 'area': '경험', 'topic': 'What will be different next year?', 'src': 'MI'},
 84: {'no': 84,
      'area': '경험',
      'topic': 'Write about the differences between last year and this year.',
      'src': 'MI'},
 85: {'no': 85,
      'area': '경험',
      'topic': 'How would you feel if your family went on a trip and you were alone for a week?',
      'src': '띵킹어학원'},
 86: {'no': 86,
      'area': '경험',
      'topic': 'Write about a gift you would like to get and the reasons why.',
      'src': '띵킹어학원'},
 87: {'no': 87,
      'area': '경험',
      'topic': 'Write about a time you received the best gift ever.',
      'src': '렉스킴'},
 88: {'no': 88, 'area': '경험', 'topic': 'What can I do if I have 20 dollars?', 'src': '렉스킴'},
 89: {'no': 89,
      'area': '경험',
      'topic': 'Write about the most memorable trip you had.',
      'src': '서초 피아이'},
 90: {'no': 90, 'area': '경험', 'topic': 'Describe a special memory.', 'src': '스와튼'},
 91: {'no': 91,
      'area': '경험',
      'topic': 'What was the most memorable day this year, and why?',
      'src': '스와튼'},
 92: {'no': 92, 'area': '경험', 'topic': 'Describe your first day of school.', 'src': '아이앤'},
 93: {'no': 93, 'area': '경험', 'topic': 'What did you do during summer vacation?', 'src': '알파'},
 94: {'no': 94, 'area': '경험', 'topic': 'Describe your daily routine after school.', 'src': '알파'},
 95: {'no': 95, 'area': '경험', 'topic': 'Write about a time you helped someone.', 'src': '에디센'},
 96: {'no': 96,
      'area': '경험',
      'topic': 'What is the best meal your family has cooked together?',
      'src': '이맥스'},
 97: {'no': 97,
      'area': '경험',
      'topic': 'Write about a time you felt proud of yourself.',
      'src': '이맥스'},
 98: {'no': 98, 'area': '경험', 'topic': 'Describe your favorite family tradition.', 'src': '인사이트'},
 99: {'no': 99, 'area': '경험', 'topic': 'Write about a time you made a new friend.', 'src': '인사이트'},
 100: {'no': 100, 'area': '경험', 'topic': 'What did you do last weekend?', 'src': '인사이트'},
 101: {'no': 101,
       'area': '경험',
       'topic': 'Write about a time you were scared and how you overcame it.',
       'src': '인사이트'},
 102: {'no': 102,
       'area': '경험',
       'topic': 'Describe a mistake you made and what you learned from it.',
       'src': '제이프렙'},
 103: {'no': 103,
       'area': '경험',
       'topic': 'Write about your favorite birthday celebration.',
       'src': '제이프렙'},
 104: {'no': 104,
       'area': '경험',
       'topic': 'What is something new you learned recently?',
       'src': '제이프렙'},
 105: {'no': 105,
       'area': '경험',
       'topic': 'Write about a time you had to wait for something you really wanted.',
       'src': '트윈클'},
 106: {'no': 106,
       'area': '자기소개',
       'topic': 'If you could have a sibling, who would you want to have?',
       'src': 'ILE'},
 107: {'no': 107,
       'area': '자기소개',
       'topic': 'Would you rather have a brother or sister?',
       'src': 'ILE'},
 108: {'no': 108,
       'area': '자기소개',
       'topic': 'What would you like to give to your best friend?',
       'src': 'MI'},
 109: {'no': 109,
       'area': '자기소개',
       'topic': 'What are some good ways to live a long and healthy life?',
       'src': 'MI'},
 110: {'no': 110, 'area': '자기소개', 'topic': 'What are you thankful for?', 'src': 'MI'},
 111: {'no': 111,
       'area': '자기소개',
       'topic': 'Who is the most admirable person to you and why?',
       'src': '띵킹어학원'},
 112: {'no': 112,
       'area': '자기소개',
       'topic': 'Why is it important to always try your best?',
       'src': '렉스킴'},
 113: {'no': 113, 'area': '자기소개', 'topic': 'Why is honesty important?', 'src': '렉스킴'},
 114: {'no': 114,
       'area': '자기소개',
       'topic': 'What are the best qualities to have as a best friend?',
       'src': '서초 피아이'},
 115: {'no': 115,
       'area': '자기소개',
       'topic': 'What kind of qualities do they need to be good teachers?',
       'src': '스와튼'},
 116: {'no': 116, 'area': '자기소개', 'topic': 'What will you do and be 10 years later?', 'src': '스와튼'},
 117: {'no': 117,
       'area': '자기소개',
       'topic': 'When your friend is feeling down and sad, what would you do?',
       'src': '스와튼'},
 118: {'no': 118, 'area': '자기소개', 'topic': 'What are three words that describe you?', 'src': '아이앤'},
 119: {'no': 119, 'area': '자기소개', 'topic': 'What is your biggest strength?', 'src': '알파'},
 120: {'no': 120,
       'area': '자기소개',
       'topic': 'What is something you want to improve about yourself?',
       'src': '이맥스'},
 121: {'no': 121, 'area': '자기소개', 'topic': 'Who inspires you the most, and why?', 'src': '인사이트'},
 122: {'no': 122,
       'area': '자기소개',
       'topic': 'What is a rule you always follow, and why?',
       'src': '제이프렙'},
 123: {'no': 123, 'area': '자기소개', 'topic': 'What makes you a good friend?', 'src': '트윈클'},
 124: {'no': 124, 'area': '자기소개', 'topic': 'What is your dream job, and why?', 'src': '트윈클'},
 125: {'no': 125, 'area': '자기소개', 'topic': 'What is something you are proud of?', 'src': '트윈클'},
 126: {'no': 126,
       'area': '학교사회',
       'topic': 'What is a present you want to give to Santa?',
       'src': 'ILE'},
 127: {'no': 127,
       'area': '학교사회',
       'topic': 'How is elementary school different from kindergarten?',
       'src': 'ILE'},
 128: {'no': 128,
       'area': '학교사회',
       'topic': 'Between Seollal and Chuseok, which holiday is more important?',
       'src': 'MI'},
 129: {'no': 129,
       'area': '학교사회',
       'topic': 'Between playing hard and studying hard, which one is more important?',
       'src': 'MI'},
 130: {'no': 130,
       'area': '학교사회',
       'topic': 'Between being clever and being kind, which one is more important?',
       'src': 'MI'},
 131: {'no': 131, 'area': '학교사회', 'topic': 'Why is it important to work?', 'src': '띵킹어학원'},
 132: {'no': 132,
       'area': '학교사회',
       'topic': 'Why do you want to come to Think-Eng English academy?',
       'src': '띵킹어학원'},
 133: {'no': 133,
       'area': '학교사회',
       'topic': 'If all the adults in the world were to disappear, how would you feel?',
       'src': '띵킹어학원'},
 134: {'no': 134,
       'area': '학교사회',
       'topic': 'Write a story about a man finding a secret door.',
       'src': '띵킹어학원'},
 135: {'no': 135,
       'area': '학교사회',
       'topic': "What would you do on a holiday? It needs to be a holiday that doesn't exist.",
       'src': '띵킹어학원'},
 136: {'no': 136, 'area': '학교사회', 'topic': 'Describe three things about you.', 'src': '띵킹어학원'},
 137: {'no': 137,
       'area': '학교사회',
       'topic': 'What are two things you want to teach your friend?',
       'src': '띵킹어학원'},
 138: {'no': 138,
       'area': '학교사회',
       'topic': 'How would you explain your good talent to others?',
       'src': '띵킹어학원'},
 139: {'no': 139,
       'area': '학교사회',
       'topic': 'How would your life change if you shrunk to the size of a hand?',
       'src': '렉스킴'},
 140: {'no': 140,
       'area': '학교사회',
       'topic': 'If a witch turned your friend into a hamster, how would you help him/her?',
       'src': '렉스킴'},
 141: {'no': 141,
       'area': '학교사회',
       'topic': 'What would you do if a tiny person as small as your hand sank you down in the '
                'water?',
       'src': '서초 피아이'},
 142: {'no': 142,
       'area': '학교사회',
       'topic': 'How would you explain what you do well to a friend of yours?',
       'src': '서초 피아이'},
 143: {'no': 143,
       'area': '학교사회',
       'topic': "If we didn't go to school anymore, how do you think your daily life and life in "
                'general would change?',
       'src': '서초 피아이'},
 144: {'no': 144,
       'area': '학교사회',
       'topic': 'If you are a superhero, what kind of power would you like to have?',
       'src': '서초 피아이'},
 145: {'no': 145,
       'area': '학교사회',
       'topic': 'If the Earth is getting polluted, what would you do to save it?',
       'src': '서초 피아이'},
 146: {'no': 146,
       'area': '학교사회',
       'topic': 'Should your parents let you watch TV whenever you want?',
       'src': '서초 피아이'},
 147: {'no': 147,
       'area': '학교사회',
       'topic': 'Is it better to work alone or work with others?',
       'src': '서초 피아이'},
 148: {'no': 148,
       'area': '학교사회',
       'topic': 'Give three reasons why students should have homework.',
       'src': '스와튼'},
 149: {'no': 149,
       'area': '학교사회',
       'topic': 'Why should homework be done before watching TV?',
       'src': '스와튼'},
 150: {'no': 150, 'area': '학교사회', 'topic': 'Why should we exercise?', 'src': '아이앤'},
 151: {'no': 151,
       'area': '학교사회',
       'topic': 'Why do you think that learning English is important? And what can you do when you '
                'learn English?',
       'src': '아이앤'},
 152: {'no': 152,
       'area': '학교사회',
       'topic': 'If you can travel anywhere in your country, where do you want to go and why?',
       'src': '아이앤'},
 153: {'no': 153,
       'area': '학교사회',
       'topic': 'What do you think about the global pandemic? Throughout history, what was the '
                "most famous pandemic's solution and lesson about that?",
       'src': '알파'},
 154: {'no': 154,
       'area': '학교사회',
       'topic': 'If toys could be alive on the night of Halloween, what would you do and why?',
       'src': '알파'},
 155: {'no': 155,
       'area': '학교사회',
       'topic': 'Describe what your city/town looks like.',
       'src': '에디센'},
 156: {'no': 156,
       'area': '학교사회',
       'topic': 'If something could disappear from the world, what would it be?',
       'src': '에디센'},
 157: {'no': 157,
       'area': '학교사회',
       'topic': 'If you could pick some subjects that you should learn, what would they be, and '
                'why?',
       'src': '이맥스'},
 158: {'no': 158, 'area': '학교사회', 'topic': 'What rules should every classroom have?', 'src': '이맥스'},
 159: {'no': 159, 'area': '학교사회', 'topic': 'Why is it important to help classmates?', 'src': '이맥스'},
 160: {'no': 160, 'area': '학교사회', 'topic': 'Should students wear school uniforms?', 'src': '인사이트'},
 161: {'no': 161, 'area': '학교사회', 'topic': 'What makes a good leader?', 'src': '인사이트'},
 162: {'no': 162, 'area': '학교사회', 'topic': 'Why is recycling important?', 'src': '제이프렙'},
 163: {'no': 163,
       'area': '학교사회',
       'topic': 'What can students do to help the environment?',
       'src': '제이프렙'},
 164: {'no': 164,
       'area': '학교사회',
       'topic': 'Should students be allowed to choose their own subjects?',
       'src': '트윈클'},
 165: {'no': 165, 'area': '학교사회', 'topic': 'Why is teamwork important in school?', 'src': '트윈클'}}
